test: &default
  PAYPAL_ENV: sandbox
  PAYPAL_CLIENT_ID: 	 	YOUR_CREDENTIAL_HERE
  PAYPAL_CLIENT_SECRET: 	YOUR_CREDENTIAL_HERE
  STRIPE_PUBLISHABLE_KEY:	pk_test_51Ie1oBIx9MpsEQHDnoz7eIQTtOH2dJQFdv79iLwPjsSHT5a0UL2q1gAtTdCqyYJWxcZEtMRANrqRP84VUxXM7uiV001EPNRmdB
  STRIPE_SECRET_KEY: 	sk_test_51Ie1oBIx9MpsEQHDzLYmGuVPqMuzsm4L4c5c7YVNa7VUOIbgO8hDw6HqK08FQtWQevvc8hH6xSpoJg5SIY7EWsMd00CPaon4Sf
development:
  <<: *default